root = "/app"
tmp_dir = "/tmp/air-cel"
[build]
cmd = "go build -o /tmp/air-cel/cel ./services/cel/cmd/server"
bin = "/tmp/air-cel/cel"
include_ext = ["go","mod"]
exclude_dir = ["ui","node_modules","tmp","vendor",".git"]
stop_on_error = true
[log]
time = true
