root = "/app"
tmp_dir = "/tmp/air-exec"
[build]
cmd = "go build -o /tmp/air-exec/execution ./services/execution/cmd/server"
bin = "/tmp/air-exec/execution"
include_ext = ["go","mod"]
exclude_dir = ["ui","node_modules","tmp","vendor",".git"]
stop_on_error = true
[log]
time = true
